version: "3.8"

x-common-variables: &common-variables
  POSTGRES_USER: ${DB_USER}
  POSTGRES_PASSWORD: ${DB_PASSWORD}

services:
  dbpostgres:
    image: postgres
    container_name: dbpostgres
    volumes:
      - dbdata:/var/lib/postgresql/data
      - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"
      - "./database_migrations:/tmp/database_migrations"
    environment:
      <<: *common-variables
      POSTGRES_HOST: localhost
    networks:
      - db_net

  caddy:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./caddy
    ports:
      - "80:80"
    networks:
      - web_net
      - api_net

  api:
    build:
      dockerfile: Dockerfile
      context: "./backend"
    depends_on:
      - dbpostgres
    environment:
      <<: *common-variables
      POSTGRES_HOST_IP: dbpostgres
      PGUSER: ${DB_USER}
      PGPASSWORD: ${DB_PASSWORD}
      PGHOST: dbpostgres
      PORT: 8080
    container_name: backend
    networks:
      - api_net
      - db_net

  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    container_name: client
    networks:
      - web_net

  startup:
    container_name: startup
    build:
      context: ./startup
      dockerfile: Dockerfile
    command: ansible-playbook /opt/playbook.yml
    volumes:
      - ./startup:/opt
      - //var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - caddy
      - dbpostgres
      - api
      - client
    networks:
      - db_net
      - web_net
      - api_net

volumes:
  dbdata:

networks:
  db_net:
  web_net:
  api_net:
