- name: Main playbook
  hosts: localhost
  gather_facts: true
  tasks:
  - name: Backup database
    community.docker.docker_container_exec:
      container: dbpostgres
      command: pg_dump -U ${DB_USER} -d ${DB_USER} -f /var/backups/db_backup.sql